---
abstract: 'choose remote host by header'
author:
  - 'Mario Domgoergen L<E<lt>mario@domgoergen.comE<gt>>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Proxy-ByHeader
provides:
  Plack::Middleware::Proxy::ByHeader:
    file: lib/Plack/Middleware/Proxy/ByHeader.pm
    version: 0.01
requires:
  Carp: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
